Flammel:
  Fission:
    templateDirectories: []
    functions:
      node: [Flammel\Fission\Functions\Node, '__invoke']
      fission: [Flammel\Fission\Functions\Fission, '__invoke']
Neos:
  Neos:
    fusion:
      autoInclude:
        Flammel.Fission: true
